name: arkit_plugin_example
description: Demonstrates how to use the arkit_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.13
  gallery_saver: ^2.3.2
  image_picker: ^0.8.7
  flutter_file_dialog: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

  arkit_plugin:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/face.jpg
    - assets/fox.jpg
    - assets/fox.png
    - assets/wireframeTexture.jpg
